web: python manage.py migrate --noinput && python manage.py setup_admin && gunicorn config.wsgi --bind 0.0.0.0:$PORT --log-file - --access-logfile - --workers 2
worker: celery -A config worker --loglevel=info --concurrency=2
