<<<<<<< HEAD
# Generated by Django 5.1.15 on 2026-05-27 09:20

import django.db.models.deletion
=======
# Generated by Django 5.1.15 on 2026-05-26 08:39

import django.db.models.deletion
import uuid
>>>>>>> 08f73c6dc1b9a9b1d4b758745c98861cb41d347c
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name="Audit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("in_progress", "En cours"),
                            ("completed", "Terminé"),
                            ("cancelled", "Annulé"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
=======
            name='AuditPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('audit', 'Audit'), ('security', 'Security'), ('protection', 'Protection'), ('premium', 'Premium')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('included_services', models.TextField(blank=True)),
                ('for_whom', models.TextField(blank=True)),
                ('perimeter', models.TextField(blank=True)),
                ('duration_days', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'audit_packs',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='AuditRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='pending', max_length=20)),
                ('scope_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_requests', to=settings.AUTH_USER_MODEL)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='audits.auditpack')),
            ],
            options={
                'db_table': 'audit_requests',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['client', '-submitted_at'], name='audit_reque_client__7a0a11_idx')],
>>>>>>> 08f73c6dc1b9a9b1d4b758745c98861cb41d347c
            },
        ),
    ]
