# Generated by Django 5.1.15 on 2026-05-27 07:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0002_seed_packs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True)),
                ('verdict', models.CharField(blank=True, max_length=255)),
                ('grade', models.CharField(choices=[('A', 'A — Excellent'), ('B+', 'B+ — Très bon'), ('B', 'B — Bon'), ('C', 'C — Moyen'), ('D', 'D — Faible'), ('E', 'E — Mauvais'), ('F', 'F — Critique')], default='C', max_length=2)),
                ('security_score', models.PositiveSmallIntegerField(default=50)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('pdf_path', models.CharField(blank=True, max_length=255)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='audits.auditrequest')),
            ],
            options={
                'db_table': 'audit_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
