# Generated by Django 5.1.15 on 2026-06-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditreport",
            name="pdf_content",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
